name: GHA Shepherd
author: Al Berez
branding:
  icon: activity
  color: red
description: Manage Shepherd environments

inputs:
  debug:
    description: Debug logging
    default:     0
  api_token:
    description: Shepherd API Token
    required:    true
  api_endpoint:
    description: Shepherd API Endpoint
    required:    true
  command:
    description: Supports shell (default), create, get, delete
    required:    true
  run:
    description: Execute this shell script within authenticated shepherd context
  env_id:
    description: If no environment id provided, claim new one
  namespace:
    description: Shepherd Namespace
    default:     tas-devex
  pool_name:
    description: Shepherd Pool Name
  pool_namespace:
    description: Shepherd Pool Namespace
    default:     official
  duration:
    description: Duration of the env lease
    default:     4h
  description:
    description: Description of the new lease
    default:     "GHA: ${{ github.repository }}"
  env_file_path:
    description: Location of the JSON env file
    default:     ./lease_env.json

outputs:
  env_id:
    description: Lease ID produced by create command

runs:
  using: docker
  image: Dockerfile
  entrypoint: /main.sh

  env:
    API_ENDPOINT:   ${{ inputs.api_endpoint }}
    API_TOKEN:      ${{ inputs.api_token }}
    COMMAND:        ${{ inputs.command }}
    DESCRIPTION:    ${{ inputs.description }}
    DURATION:       ${{ inputs.duration }}
    ENV_FILE_PATH:  ${{ inputs.env_file_path }}
    ENV_ID:         ${{ inputs.env_id }}
    NAMESPACE:      ${{ inputs.namespace }}
    POOL_NAME:      ${{ inputs.pool_name }}
    POOL_NAMESPACE: ${{ inputs.pool_namespace }}
    RUN:            ${{ inputs.run }}
    TRACE:          ${{ inputs.debug }}
  